// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/kir0108/PayShareBackend/internal/data/postgres"
	"github.com/kir0108/PayShareBackend/internal/data/redis"
	"github.com/kir0108/PayShareBackend/internal/jwt"
)

// Injectors from wire.go:

func initApp() (*application, func(), error) {
	mainConfig, err := getConfig()
	if err != nil {
		return nil, nil, err
	}
	sugaredLogger, cleanup, err := newLogger(mainConfig)
	if err != nil {
		return nil, nil, err
	}
	jwtConfig := newJwtConfig(mainConfig)
	manager := jwt.NewManger(jwtConfig)
	redisConfig := newRedisConfig(mainConfig)
	pool, cleanup2 := redis.NewRedisPool(redisConfig, sugaredLogger)
	codesRepository := redis.NewCodesRepository(pool, redisConfig)
	postgresConfig := newPostgresConfig(mainConfig)
	pgxpoolPool, cleanup3, err := postgres.NewPsqlPool(postgresConfig)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	userRepo := &postgres.UserRepo{
		DB: pgxpoolPool,
	}
	refreshTokenRepository, cleanup4 := redis.NewRefreshTokenRepository(pool, redisConfig, sugaredLogger)
	api := newAPI(mainConfig)
	mainApplication := &application{
		config:        mainConfig,
		logger:        sugaredLogger,
		jwts:          manager,
		codes:         codesRepository,
		users:         userRepo,
		refreshTokens: refreshTokenRepository,
		api:           api,
	}
	return mainApplication, func() {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
